# Generated by Django 5.0 on 2025-11-27 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_state",
                    models.JSONField(help_text="Complete game state as JSON"),
                ),
                ("day", models.IntegerField(default=1)),
                ("employment", models.FloatField(default=0.0)),
                ("inflation", models.FloatField(default=0.0)),
                ("services_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_saves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["-updated_at"], name="game_gamesa_updated_7169a0_idx"
                    ),
                    models.Index(
                        fields=["user", "-updated_at"],
                        name="game_gamesa_user_id_5229df_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HighScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initials",
                    models.CharField(
                        default="AAA",
                        help_text="3-letter initials for leaderboard display (classic arcade style)",
                        max_length=3,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("final_day", models.IntegerField(default=1)),
                ("employment", models.FloatField(default=0.0)),
                ("inflation", models.FloatField(default=0.0)),
                ("services", models.FloatField(default=0.0)),
                ("achieved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: linked user account",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="high_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "-achieved_at"],
                "indexes": [
                    models.Index(
                        fields=["-score"], name="game_highsc_score_cc3fc3_idx"
                    ),
                    models.Index(
                        fields=["user", "-score"], name="game_highsc_user_id_349dff_idx"
                    ),
                    models.Index(
                        fields=["-achieved_at"], name="game_highsc_achieve_3bc387_idx"
                    ),
                ],
            },
        ),
    ]
